#pragma once

void default_constants();
void drive_and_turn();
void wait_until_change_speed();
void swing_example();
void motion_chaining();
void combining_movements();
void interfered_example();
void odom_drive_example();
void odom_pure_pursuit_example();
void odom_pure_pursuit_wait_until_example();
void odom_boomerang_example();
void odom_boomerang_injected_pure_pursuit_example();
void measure_offsets();
void auto_wp_left();
void auto_wp_right();
void left_sweep();
void right_sweep();
void left_contest();
void right_contest();
void skills();